name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: love-Liushuang/NotionNext
          ref: main

      - name: Push changes to new repository
        run: |
          git remote add new-origin https://github.com/love-Liushuang/NotionNextOutside.git
          git push -u new-origin main --force
